path: ''

adducts: ['+Na', '+H', '-H', 'Ne']
charges: {'+Na': 1, '+H': 1, '-H': -1, 'Ne': 0}

forcefield:
  type: 'gaff'
  steps: 500

impact:
  shotsPerRot: 64
  convergence: 0.001
  nRuns: 64
  seed: 0

ccs:
  alpha: 27.9
  beta: 0.14

amber:
  cycles: 10
  nframes: 10
  low: 1.25e+06
  high: 1.45e+06

nwchem:
  dft_template: default
  shielding_template: default

mobcal:
  params: default
  atomtypes: default
  exe: mobcal_cascade
