path: ''

adducts: ['+Na', '+H', '-H', 'Ne']
charges: {'+Na': 1, '+H': 1, '-H': -1, 'Ne': 0}

forcefield:
  type: 'gaff'
  steps: 500

impact:
  shotsPerRot: 64
  convergence: 0.001
  nRuns: 64
  seed: 0

ccs:
  alpha: 27.9
  beta: 0.14

amber:
  cycles: 2
  nframes: 10
  low: 1.25e+06
  high: 1.45e+06

nwchem:
  runscript: isicle/resources/nwchem/cascade.sh
  dft_template: isicle/resources/nwchem/dft.template
  shielding_template: isicle/resources/nwchem/shielding.template

mobcal:
  params: isicle/resources/mobcal/mobcal.params
  atomtypes: isicle/resources/mobcal/atomtype_parameters.in
  runscript: isicle/resources/mobcal/cascade.sh
